#!/usr/bin/env python3
"""Generate all output files for episode 6jvskRWvQkg extraction."""
import json
import os

BASE = '/Users/ido.kazma/Desktop/Projects/private/where2eat'
VIDEO_ID = '6jvskRWvQkg'
PUBLISHED = '2025-12-31'
CHANNEL = 'מדברים מהבטן - הפודיום'
EPISODE_ID = 'a6564baa-0913-4df7-a91a-e2dd968f53da'

# Read enrichment for Google Places data
with open(f'{BASE}/analyses/{VIDEO_ID}/enrichment.json') as f:
    enrichment = json.load(f)

enr = enrichment['restaurants']

# Restaurant definitions for ADD TO PAGE
restaurants = [
    {
        "slug": "mari_posa",
        "name_hebrew": "מרי פוסה",
        "name_english": "Mariposa",
        "city": "קיסריה",
        "neighborhood": None,
        "address": "מגרש הגולף, קיסריה",
        "region": "שרון",
        "cuisine_type": "שף",
        "status": "פתוח",
        "price_range": "יקר",
        "host_opinion": "חיובית מאוד",
        "host_comments": "יונתן בוחר את החמוסטה התאילנדית של השף חביב משה כביס השנה. ציר עוף תאילנדי, שום, צ'ילי, קפיר ליים. מסעדה נהדרת באזור הגולף בקיסריה.",
        "menu_items": ["חמוסטה תאילנדית", "קובות עם גרס וג'ינג'ר"],
        "special_features": ["מסעדת שף", "מטבח ישראלי-תאילנדי", "אזור הגולף"],
        "mention_context": "ביס השנה מספר 1 של יונתן כהן - חמוסטה תאילנדית מופלאה",
        "mention_timestamp_seconds": 412,
        "engaging_quote": "זו מסעדה נהדרת והיא אופציה מעולה לכל מי שחי ונמצא שם באזור",
        "enr_key": "מרי פוסה",
        "is_closing": 0,
    },
    {
        "slug": "mashya",
        "name_hebrew": "משיה",
        "name_english": "Mashya",
        "city": "תל אביב",
        "neighborhood": None,
        "address": "מנדלי מוכר ספרים 5, תל אביב",
        "region": "מרכז",
        "cuisine_type": "שף",
        "status": "פתוח",
        "price_range": "יקר",
        "host_opinion": "חיובית מאוד",
        "host_comments": "עמית בוחר את מנת הסקלופ צלוי, קלמרי ממולא צ'וריסו, ניוקי אורז וציר חמוסטה של גיל דהן כביס השנה. שילוב מבריק של חדש וישן.",
        "menu_items": ["סקלופ צלוי", "קלמרי ממולא צ'וריסו", "ניוקי אורז", "ציר חמוסטה"],
        "special_features": ["מטבח ישראלי חדש", "שף גיל דהן"],
        "mention_context": "ביס השנה מספר 1 של עמית אהרונסון",
        "mention_timestamp_seconds": 470,
        "engaging_quote": "פיצוץ של טעמים מהסוג שלא תוכלו למצוא באחריות בשום מקום אחר בעולם",
        "enr_key": "משיה",
        "is_closing": 0,
    },
    {
        "slug": "gourmet_sabzi",
        "name_hebrew": "גורמה סבזי",
        "name_english": "Gourmet Sabzi",
        "city": "תל אביב",
        "neighborhood": "שוק לוינסקי",
        "address": "לוינסקי 47, תל אביב",
        "region": "מרכז",
        "cuisine_type": "פרסי",
        "status": "פתוח",
        "price_range": "זול",
        "host_opinion": "חיובית מאוד",
        "host_comments": "נטע בוחרת את הגונדי כביס השנה. ציר עוף איכותי עם קורכום ומקופטה. ביס שניחם אותה כל השנה.",
        "menu_items": ["גונדי", "ציר עוף עם קורכום", "קופטה"],
        "special_features": ["מטבח פרסי", "שוק לוינסקי"],
        "mention_context": "ביס השנה מספר 1 של נטע סלונים - הגונדי האחד והיחיד",
        "mention_timestamp_seconds": 513,
        "engaging_quote": "קופטה נפלאה, ביס מהחלומות לכל שעה ביום",
        "enr_key": "גורמה סבזי",
        "is_closing": 0,
    },
    {
        "slug": "mijena",
        "name_hebrew": "מיז'נה",
        "name_english": "Mijana",
        "city": "חיפה",
        "neighborhood": "הדר הכרמל",
        "address": None,
        "region": "צפון",
        "cuisine_type": "ערבי מודרני",
        "status": "פתוח",
        "price_range": "בינוני",
        "host_opinion": "חיובית מאוד",
        "host_comments": "יונתן בוחר את הקובות המתוגנות כביס שנה. מסעדה ערבית מודרנית בחיפה עם חותם של השף עומר אלואן. קובות על יוגורט במרקם משוגע.",
        "menu_items": ["קובות מתוגנות", "קובות על יוגורט"],
        "special_features": ["מסעדה ערבית מודרנית", "השפעת עומר אלואן"],
        "mention_context": "ביס השנה מספר 2 של יונתן כהן - הקובה המתוגנת הטובה במזרח התיכון",
        "mention_timestamp_seconds": 535,
        "engaging_quote": "זו הקובה המתוגנת הטובה במזרח התיכון",
        "enr_key": "מיז׳נה",  # wrong match, no google data to use
        "skip_enr": True,
        "is_closing": 0,
    },
    {
        "slug": "al_kaber",
        "name_hebrew": "אלקבר",
        "name_english": "Al Kaber",
        "city": "עין זיוון",
        "neighborhood": None,
        "address": "כניסה לעין זיוון, רמת הגולן",
        "region": "צפון",
        "cuisine_type": "אוכל רחוב",
        "status": "פתוח",
        "price_range": "זול",
        "host_opinion": "חיובית מאוד",
        "host_comments": "עמית בוחר את בייגל הקריספי צ'יקן של אלקבר. פוד טראק בכניסה לעין זיוון בגולן. נתח עוף עסיסי, קולסלו, רוטב ברביקיו ביתי.",
        "menu_items": ["בייגל קריספי צ'יקן", "קולסלו", "רוטב ברביקיו ביתי"],
        "special_features": ["פוד טראק", "צפון", "אוכל רחוב"],
        "mention_context": "ביס השנה של עמית אהרונסון - הצדעה לצפון",
        "mention_timestamp_seconds": 596,
        "engaging_quote": "אחרי ביס אחד באמת זה מהמנות האלה שלא אכפת לכם מי מסתכל עליכם",
        "enr_key": "אלקבר",  # wrong match
        "skip_enr": True,
        "is_closing": 0,
    },
    {
        "slug": "hastakia",
        "name_hebrew": "הסתקייה",
        "name_english": "Hastakia",
        "city": "ירושלים",
        "neighborhood": "מחנה יהודה",
        "address": None,
        "region": "ירושלים",
        "cuisine_type": "מזרחי",
        "status": "פתוח",
        "price_range": "בינוני",
        "host_opinion": "חיובית מאוד",
        "host_comments": "יונתן בוחר את חומוס חשויה כביס שנה. מסעדה של אסף גרנית וקבוצת מחנה יהודה. חומוס עם בשר טחון מטוגן ממושכות - קומבינציה אלוהית.",
        "menu_items": ["חומוס חשויה", "קבב", "ראשונות יצירתיות"],
        "special_features": ["קבוצת מחנה יהודה", "אסף גרנית"],
        "mention_context": "ביס השנה מספר 3 של יונתן כהן - המסעדה הכי טעימה של אסף גרנית",
        "mention_timestamp_seconds": 707,
        "engaging_quote": "חומוס חשויה...קומבינציה אלוהית של בשר טחון מטוגן ממושכות על חומוס נהדר",
        "enr_key": "השתאקייה",  # wrong match
        "skip_enr": True,
        "is_closing": 0,
    },
    {
        "slug": "hallansan",
        "name_hebrew": "הלנסן",
        "name_english": "Hallansan",
        "city": "תל אביב",
        "neighborhood": None,
        "address": None,
        "region": "מרכז",
        "cuisine_type": "קוריאני",
        "status": "פתוח",
        "price_range": "בינוני",
        "host_opinion": "חיובית מאוד",
        "host_comments": "נטע בוחרת את פסטת הפיצ'י של הלנסן כביס שנה. רוטב בועט מפולפל וחריף. לא נפלה ממנות שאכלה באיטליה.",
        "menu_items": ["פיצ'י פפה", "רוטב חריף מפולפל"],
        "special_features": ["מסעדה קוריאנית", "פסטה"],
        "mention_context": "ביס השנה של נטע סלונים - פסטה שלא נופלת מאיטליה",
        "mention_timestamp_seconds": 856,
        "engaging_quote": "המנה הזו לא נפלה אם לא הובילה על מנות שהיו באיטליה",
        "enr_key": "הלנסן",  # wrong match
        "skip_enr": True,
        "is_closing": 0,
    },
    {
        "slug": "zafririm",
        "name_hebrew": "צפרירים",
        "name_english": "Zafririm",
        "city": "חיפה",
        "neighborhood": None,
        "address": "צפרירים 1, חיפה",
        "region": "צפון",
        "cuisine_type": "בשרים",
        "status": "פתוח",
        "price_range": "בינוני",
        "host_opinion": "חיובית מאוד",
        "host_comments": "יונתן בוחר את השוארמה כביס שנה. ביסטרו ותיק בחיפה שפתח מנגליה עם עמוד שוארמה של עגל וכבש. בטופ השוארמות בחיפה.",
        "menu_items": ["שוארמה עגל וכבש"],
        "special_features": ["ביסטרו ותיק", "שוארמה", "מנגליה"],
        "mention_context": "ביס השנה מספר 4 של יונתן כהן - בטופ השוארמות בחיפה",
        "mention_timestamp_seconds": 901,
        "engaging_quote": "זה היום בטופ של השוארמות בחיפה ולהיות בטופ של השוארמות בחיפה זה לא עניין של מה בכך",
        "enr_key": "צפרירים",
        "is_closing": 0,
    },
    {
        "slug": "chacoli",
        "name_hebrew": "צ'קולי",
        "name_english": "Chacoli",
        "city": "תל אביב",
        "neighborhood": "טיילת הרברט סמואל",
        "address": "רציף הרברט סמואל 3, תל אביב",
        "region": "מרכז",
        "cuisine_type": "ספרדי",
        "status": "פתוח",
        "price_range": "יקר",
        "host_opinion": "חיובית מאוד",
        "host_comments": "עמית בוחר את צ'קולי כמסעדת השנה. מסעדת טאפס ספרדית על הטיילת של ירדן שי. שפית השנה. תחושה של נורמליות ועיר עם חוף ים.",
        "menu_items": ["טאפס", "עששים עם פרלינאה", "טטקי דג חרב", "סלט עגבניות", "קרוקט אחי עגל"],
        "special_features": ["טאפס ספרדי", "טיילת", "שפית השנה - ירדן שי"],
        "mention_context": "מסעדת השנה של עמית אהרונסון ושפית השנה - ירדן שי",
        "mention_timestamp_seconds": 1077,
        "engaging_quote": "מסעדה שמציאה את המצרך הכי חשוב לכולנו - תחושה של נורמליות",
        "enr_key": "צ׳קולי",
        "is_closing": 0,
    },
    {
        "slug": "studio_gursha",
        "name_hebrew": "סטודיו גורושה",
        "name_english": "Studio Gursha",
        "city": "תל אביב",
        "neighborhood": None,
        "address": "שלמה 13, תל אביב",
        "region": "מרכז",
        "cuisine_type": "שף",
        "status": "פתוח",
        "price_range": "יקר",
        "host_opinion": "חיובית מאוד",
        "host_comments": "יונתן בוחר את סטודיו גורושה כמסעדת השנה כבר מיוני 2025. משהו שונה לחלוטין שלא היה פה הרבה שנים. עומד במבחן הזמן בהצלחה.",
        "menu_items": [],
        "special_features": ["שף אלעזר", "מטבח חדשני", "ברנץ' חדש"],
        "mention_context": "מסעדת השנה של יונתן כהן - כזו כמו סטודיו גורשה אין",
        "mention_timestamp_seconds": 1199,
        "engaging_quote": "כזו כמו סטודיו גורשה אין וגם הרבה שנים לא הייתה",
        "enr_key": "סטודיו גורושה",
        "is_closing": 0,
    },
    {
        "slug": "prino",
        "name_hebrew": "פרינו",
        "name_english": "Farino / Prino",
        "city": "אשדוד",
        "neighborhood": None,
        "address": "האשל 9, אשדוד",
        "region": "דרום",
        "cuisine_type": "פיצה",
        "status": "פתוח",
        "price_range": "בינוני",
        "host_opinion": "חיובית מאוד",
        "host_comments": "נטע בוחרת את קומפלקס פרינו/פת באשדוד כמסעדת השנה. פיצריה נפוליטנית של יאן ארוש. אמן ברמת הבצק עם ביסים עוצמתיים וזכירים.",
        "menu_items": ["פיצה נפוליטנית", "פוקצ'ה", "טירמיסו"],
        "special_features": ["פיצריה נפוליטנית", "יאן ארוש", "קומפלקס פת+פרינו"],
        "mention_context": "מסעדת השנה של נטע סלונים - הפיאצה האיטלקית של יאן ארוש באשדוד",
        "mention_timestamp_seconds": 1329,
        "engaging_quote": "שילוב הטעמים, היכולת שלו לפתח ביסים כל כך עוצמתיים בסך הכל בפיצה - מדהים",
        "enr_key": "פרינו",
        "is_closing": 0,
    },
    {
        "slug": "moshik",
        "name_hebrew": "מושיק",
        "name_english": "Moshik",
        "city": "תל אביב",
        "neighborhood": None,
        "address": None,
        "region": "מרכז",
        "cuisine_type": "שף",
        "status": "פתוח",
        "price_range": "יקר מאוד",
        "host_opinion": "חיובית מאוד",
        "host_comments": "נטע בוחרת את הארוחה במושיק כארוחת השנה. ארוחת טעימות ב-950 שקל. היכולת לחבר חומוס וקביאר זה גאונות. ארוחה שגבלה בשלמות.",
        "menu_items": ["טרטלט אבוקדו קביאר חומוס", "ברוסקטה מרנגז", "סלט שירן", "מחמצת", "ירקות עונתיים"],
        "special_features": ["ארוחת טעימות", "מטבח פתוח", "מחמצת בת 22 שנה"],
        "mention_context": "ארוחת השנה של נטע סלונים - ארוחה שגבלה בשלמות",
        "mention_timestamp_seconds": 1521,
        "engaging_quote": "היכולת לחבר חומוס וקביאר זה לא פחות מגאונות",
        "enr_key": "מושיק",  # wrong match
        "skip_enr": True,
        "is_closing": 0,
    },
]

# Generate upload-ready JSONs
for r in restaurants:
    enr_key = r.get('enr_key')
    skip_enr = r.get('skip_enr', False)
    e = enr.get(enr_key, {}) if not skip_enr else {}

    ts = r['mention_timestamp_seconds']

    output = {
        "name_hebrew": r['name_hebrew'],
        "name_english": r['name_english'],
        "city": r['city'],
        "neighborhood": r['neighborhood'],
        "address": r.get('address') or e.get('formatted_address'),
        "region": r['region'],
        "cuisine_type": r['cuisine_type'],
        "status": r['status'],
        "price_range": r['price_range'],
        "host_opinion": r['host_opinion'],
        "host_comments": r['host_comments'],
        "menu_items": r['menu_items'],
        "special_features": r['special_features'],
        "contact_hours": None,
        "contact_phone": e.get('phone'),
        "contact_website": e.get('website'),
        "business_news": None,
        "mention_context": r['mention_context'],
        "mention_timestamp_seconds": ts,
        "youtube_timestamped_url": f"https://www.youtube.com/watch?v={VIDEO_ID}&t={int(ts)}s",
        "google_place_id": e.get('place_id'),
        "google_rating": e.get('rating'),
        "google_user_ratings_total": e.get('review_count'),
        "latitude": e.get('latitude'),
        "longitude": e.get('longitude'),
        "image_url": e.get('photo_url'),
        "photos": [],
        "google_name": e.get('google_name'),
        "published_at": PUBLISHED,
        "og_image_url": None,
        "is_closing": r['is_closing'],
        "video_url": f"https://www.youtube.com/watch?v={VIDEO_ID}",
        "video_id": VIDEO_ID,
        "channel_name": CHANNEL,
        "google_url": e.get('google_url'),
        "engaging_quote": r['engaging_quote'],
        "country": "Israel",
        "episode_id": EPISODE_ID,
        "instagram_url": e.get('instagram_url'),
    }

    # Add photos if available
    if e.get('photos'):
        for p in e['photos'][:5]:
            photo_entry = {
                "photo_reference": p.get('photo_reference', ''),
                "width": p.get('width', 0),
                "height": p.get('height', 0),
                "resolved_url": p.get('resolved_url', '')
            }
            output["photos"].append(photo_entry)

    path = f"{BASE}/data/restaurants/{VIDEO_ID}_{r['slug']}.json"
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2)
    print(f"Wrote: {path}")

print(f"\nGenerated {len(restaurants)} restaurant JSONs.")
