#!/usr/bin/env python3
"""
Validate upload-ready restaurant JSONs against production schema.

Checks structure, field names, value formats, and data completeness
to catch issues before uploading to production.

Usage:
    python scripts/validate_restaurant_jsons.py data/restaurants/VIDEO_ID/
    python scripts/validate_restaurant_jsons.py data/restaurants/VIDEO_ID/specific_file.json
"""

import json
import sys
import glob
from pathlib import Path

# Expected fields in production API response
REQUIRED_FIELDS = {
    "name_hebrew",      # str, Hebrew
    "published_at",     # str, YYYY-MM-DD
    "video_id",         # str
    "video_url",        # str, YouTube URL
}

EXPECTED_FIELDS = {
    "name_hebrew", "name_english", "city", "neighborhood", "address", "region",
    "cuisine_type", "status", "price_range", "host_opinion", "host_comments",
    "menu_items", "special_features", "contact_hours", "contact_phone",
    "contact_website", "business_news", "mention_context",
    "mention_timestamp_seconds", "youtube_timestamped_url",
    "google_place_id", "google_rating", "google_user_ratings_total",
    "latitude", "longitude", "image_url", "photos", "google_name",
    "published_at", "og_image_url", "is_closing",
    "video_url", "video_id", "channel_name", "google_url",
    "engaging_quote", "country", "episode_id", "instagram_url",
}

# Fields that should NOT be in upload JSONs (auto-generated by API)
FORBIDDEN_FIELDS = {"id", "created_at", "updated_at", "is_hidden"}

# Valid Hebrew enum values
VALID_STATUS = {"פתוח", "חדש", "נסגר", "נסגר זמנית", "עומד להיפתח"}
VALID_OPINION = {"חיובית מאוד", "חיובית", "שלילית", "מעורבת", "ניטרלית"}
VALID_PRICE = {"זול", "בינוני", "יקר", "יקר מאוד"}
VALID_REGION = {"מרכז", "צפון", "דרום", "שרון", "ירושלים", "שפלה", "חו\"ל"}

# English values that indicate the agent used wrong format
ENGLISH_STATUS = {"open", "closed", "new", "temporarily_closed", "opening_soon"}
ENGLISH_OPINION = {"very_positive", "positive", "negative", "mixed", "neutral"}
ENGLISH_PRICE = {"$", "$$", "$$$", "$$$$", "cheap", "moderate", "expensive", "very_expensive"}


def validate_file(filepath: str) -> list:
    """Validate a single restaurant JSON file. Returns list of issues."""
    issues = []

    try:
        with open(filepath, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        return [f"FATAL: Invalid JSON: {e}"]
    except Exception as e:
        return [f"FATAL: Cannot read file: {e}"]

    name = data.get("name_hebrew", Path(filepath).name)

    # Check forbidden fields
    for field in FORBIDDEN_FIELDS:
        if field in data:
            issues.append(f"FORBIDDEN field '{field}' present — API auto-generates this")

    # Check required fields
    for field in REQUIRED_FIELDS:
        if not data.get(field):
            issues.append(f"MISSING required field '{field}'")

    # Check expected fields
    missing = EXPECTED_FIELDS - set(data.keys())
    if missing:
        issues.append(f"MISSING fields: {sorted(missing)}")

    extra = set(data.keys()) - EXPECTED_FIELDS - FORBIDDEN_FIELDS
    if extra:
        issues.append(f"EXTRA fields (not in prod schema): {sorted(extra)}")

    # Field name checks
    if "mention_timestamp" in data and "mention_timestamp_seconds" not in data:
        issues.append("WRONG field name: 'mention_timestamp' should be 'mention_timestamp_seconds'")

    # Status — must be Hebrew
    status = data.get("status")
    if status:
        if status.lower() in ENGLISH_STATUS:
            issues.append(f"status='{status}' is English — must be Hebrew: {VALID_STATUS}")
        elif status not in VALID_STATUS:
            issues.append(f"status='{status}' not in valid set: {VALID_STATUS}")

    # Host opinion — must be Hebrew
    opinion = data.get("host_opinion")
    if opinion:
        if opinion.lower() in ENGLISH_OPINION:
            issues.append(f"host_opinion='{opinion}' is English — must be Hebrew: {VALID_OPINION}")
        elif opinion not in VALID_OPINION:
            issues.append(f"host_opinion='{opinion}' not in valid set: {VALID_OPINION}")

    # Price range — must be Hebrew
    price = data.get("price_range")
    if price:
        if price in ENGLISH_PRICE:
            issues.append(f"price_range='{price}' is English/$ format — must be Hebrew: {VALID_PRICE}")
        elif price not in VALID_PRICE:
            issues.append(f"price_range='{price}' not in valid set: {VALID_PRICE}")

    # Region check
    region = data.get("region")
    if region and region not in VALID_REGION:
        issues.append(f"region='{region}' not in valid set: {VALID_REGION}")

    # is_closing — must be int 0/1, not bool
    is_closing = data.get("is_closing")
    if is_closing is not None:
        if isinstance(is_closing, bool):
            issues.append(f"is_closing={is_closing} is boolean — must be int (0 or 1)")
        elif is_closing not in (0, 1):
            issues.append(f"is_closing={is_closing} must be 0 or 1")

    # mention_timestamp_seconds — must be number
    ts = data.get("mention_timestamp_seconds")
    if ts is not None and not isinstance(ts, (int, float)):
        issues.append(f"mention_timestamp_seconds must be a number, got {type(ts).__name__}")

    # youtube_timestamped_url
    yt_url = data.get("youtube_timestamped_url")
    if not yt_url:
        issues.append("MISSING youtube_timestamped_url")
    elif "&t=" not in yt_url:
        issues.append(f"youtube_timestamped_url missing &t= parameter: '{yt_url}'")

    # photos — must be list of objects, not strings
    photos = data.get("photos", [])
    if photos:
        if isinstance(photos[0], str):
            issues.append("photos is list of strings — must be list of objects with {photo_reference, width, height, resolved_url}")
        elif isinstance(photos[0], dict):
            required_photo_keys = {"photo_reference", "width", "height", "resolved_url"}
            photo_keys = set(photos[0].keys())
            missing_photo = required_photo_keys - photo_keys
            if missing_photo:
                issues.append(f"photos[0] missing keys: {missing_photo}")

    # image_url — must be resolved lh3 URL
    img = data.get("image_url")
    if img:
        if "googleapis.com/maps/api/place/photo" in img:
            issues.append("image_url is a Google API reference URL — must be resolved lh3.googleusercontent.com URL")
        elif "lh3.googleusercontent.com" not in img:
            issues.append(f"image_url doesn't look like a Google Places photo: '{img[:60]}...'")

    # instagram_url format
    insta = data.get("instagram_url")
    if insta and "instagram.com" not in insta:
        issues.append(f"instagram_url doesn't look like Instagram: '{insta}'")

    # channel_name should not be null
    if not data.get("channel_name"):
        issues.append("channel_name is null/missing — should be the podcast name")

    # engaging_quote check
    quote = data.get("engaging_quote")
    if not quote:
        issues.append("MISSING engaging_quote")
    elif len(quote) > 150:
        issues.append(f"engaging_quote too long ({len(quote)} chars) — keep under ~150")

    # Coordinates sanity (Israel: lat 29-34, lng 34-36; allow international)
    lat = data.get("latitude")
    lng = data.get("longitude")
    country = data.get("country", "Israel")
    if lat and lng and country == "Israel":
        if not (29 <= lat <= 34):
            issues.append(f"latitude={lat} out of Israel range (29-34)")
        if not (34 <= lng <= 36):
            issues.append(f"longitude={lng} out of Israel range (34-36)")

    # published_at format
    pub = data.get("published_at")
    if pub and len(pub) < 10:
        issues.append(f"published_at='{pub}' doesn't look like YYYY-MM-DD")

    return issues


def main():
    if len(sys.argv) < 2:
        print("Usage: python scripts/validate_restaurant_jsons.py <path>")
        print("  <path> can be a directory or a single .json file")
        sys.exit(1)

    target = sys.argv[1]
    if Path(target).is_file():
        files = [target]
    elif Path(target).is_dir():
        files = sorted(glob.glob(f"{target}/*.json"))
    else:
        print(f"Error: {target} is not a file or directory")
        sys.exit(1)

    if not files:
        print(f"No .json files found in {target}")
        sys.exit(1)

    total_issues = 0
    files_with_issues = 0

    print(f"Validating {len(files)} restaurant JSON(s)...\n")

    for fpath in files:
        issues = validate_file(fpath)
        name = Path(fpath).name

        if issues:
            files_with_issues += 1
            total_issues += len(issues)
            print(f"⚠️  {name}:")
            for issue in issues:
                print(f"    {issue}")
            print()
        else:
            print(f"✅ {name}")

    print(f"\n{'=' * 50}")
    print(f"Files: {len(files)} | Issues: {total_issues} | Files with issues: {files_with_issues}")
    if total_issues == 0:
        print("All files valid! ✅")
    else:
        print(f"Fix {total_issues} issue(s) before uploading to production.")
    print(f"{'=' * 50}")

    sys.exit(1 if total_issues > 0 else 0)


if __name__ == "__main__":
    main()
