"""
Configuration settings for Where2Eat backend services.
"""

import os

# YouTube Transcript Collector Settings
YOUTUBE_TRANSCRIPT_RATE_LIMIT_SECONDS = 30  # Minimum seconds between API requests
YOUTUBE_TRANSCRIPT_CACHE_ENABLED = True  # Enable database caching

# Pipeline Scheduler Settings
PIPELINE_POLL_INTERVAL_HOURS = int(os.getenv('PIPELINE_POLL_INTERVAL_HOURS', '3'))
PIPELINE_PROCESS_INTERVAL_MINUTES = int(os.getenv('PIPELINE_PROCESS_INTERVAL_MINUTES', '10'))
PIPELINE_MAX_RETRY_ATTEMPTS = int(os.getenv('PIPELINE_MAX_RETRY_ATTEMPTS', '3'))
PIPELINE_MAX_INITIAL_VIDEOS = int(os.getenv('PIPELINE_MAX_INITIAL_VIDEOS', '50'))
PIPELINE_MAX_RECENT_VIDEOS = int(os.getenv('PIPELINE_MAX_RECENT_VIDEOS', '10'))
PIPELINE_MAX_VIDEO_AGE_DAYS = int(os.getenv('PIPELINE_MAX_VIDEO_AGE_DAYS', '90'))
PIPELINE_STALE_TIMEOUT_HOURS = int(os.getenv('PIPELINE_STALE_TIMEOUT_HOURS', '2'))
PIPELINE_LOG_RETENTION_DAYS = int(os.getenv('PIPELINE_LOG_RETENTION_DAYS', '30'))
PIPELINE_SCHEDULER_ENABLED = os.getenv('PIPELINE_SCHEDULER_ENABLED', 'true').lower() == 'true'
